In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('http://bit.ly/autompg.csv')
df.head()

HTTPError: HTTP Error 404: Not Found

In [9]:
%matplotlib inline
df.plot.scatter(x='hp' , y ='mpg')

NameError: name 'df' is not defined

In [11]:
import sys

In [14]:
print(sys.version)

3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]


In [16]:
import platform

In [19]:
platform.python_version()

'3.8.8'

In [21]:
#A hello world example
print('hello world')

hello world


In [23]:
3+5


8

In [24]:
8*4

32

In [25]:
x=3
type(x)

int

In [26]:
y=2.1
type(y)

float

In [27]:
z = 'test'
type(z)

str

In [28]:
first_string_variable = 'test'
first_int_variable = 123

In [29]:
print(first_string_variable)

test


In [2]:
first_tuple = (12, 'Jack', 56.3, "new" , (3,2), "test")

In [31]:
first_tuple

(12, 'Jack', 56.3, 'new', (3, 2), 'test')

In [32]:
first_tuple[1]

'Jack'

In [3]:
first_tuple[1:4]

('Jack', 56.3, 'new')

In [4]:
first_tuple[1:-1]

('Jack', 56.3, 'new', (3, 2))

In [5]:
first_list = [1,'Mark',2.3, 'test', None, 11]

In [14]:
first_list

[1, 'Mark', 'new', 'test', None, 11]

In [7]:
first_list.append(2)

In [9]:
first_list.remove(2)

In [11]:
first_list.pop(2)

2.3

In [12]:
first_list.insert(2, 'new')

In [15]:
fname= 'George'

In [17]:
lname= 'Washington'

In [19]:
full_name = fname +lname

In [20]:
full_name = 'fname'+'lname'

In [22]:
fname

'George'

In [23]:
lname

'Washington'

In [24]:
full = fname + lname


In [25]:
full = fname + '' + lname

In [26]:
fname = 'Aliya'

In [27]:
lname = 'Shaikh'

In [28]:
full = fname + lname

In [29]:
full

'AliyaShaikh'

In [31]:
full = fname +' '+lname

In [32]:
full

'Aliya Shaikh'

In [33]:
def add_two_numbers(num1, num2):return num1+num2

In [34]:
number1 = 23
number2 = 23

In [38]:
result = add_two_numbers(number1, number2)

In [39]:
result

46.6

In [37]:
number2 = 23.6

In [40]:
def profile():

SyntaxError: unexpected EOF while parsing (<ipython-input-40-0926e88b7197>, line 1)

In [54]:
def profile():
    age = 23
    height = 5.5
    weight = 130
    return age, height, weight

In [42]:
print profile()

SyntaxError: invalid syntax (<ipython-input-42-705bc29da96f>, line 1)

In [43]:
profile()

(23, 5.5, 130)

In [44]:
newresult = profile()

In [45]:
newresult

(23, 5.5, 130)

In [46]:
print newresult

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(newresult)? (<ipython-input-46-c4a394f2b6f7>, line 1)

In [47]:
print (newresult)

(23, 5.5, 130)


In [48]:
print(profile())

(23, 5.5, 130)


In [49]:
print age

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age)? (<ipython-input-49-8aa35324a0f2>, line 1)

In [50]:
print(age)

NameError: name 'age' is not defined

In [51]:
print age, height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age, height, weight)? (<ipython-input-51-1ece668ff2de>, line 1)

In [55]:
age, height, weight = profile()

In [57]:
print age, height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age, height, weight)? (<ipython-input-57-1ece668ff2de>, line 1)

In [58]:
def profile():
    age = 23
    height = 5.5
    weight = 130
    return age, height, weight

In [59]:
age, height, weight = profile()

In [60]:
print age, height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age, height, weight)? (<ipython-input-60-1ece668ff2de>, line 1)

In [61]:
def profile():
    age = 23
    height = 5.5
    weight = 130
    return age, height, weight
age, height, weight = profile()

In [62]:
print age, height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age, height, weight)? (<ipython-input-62-1ece668ff2de>, line 1)

In [63]:
def profile():
    age = 21
    height = 5.5
    weight = 130
    return age, height, weight

age, height, weight = profile()

In [64]:
print age, height, weight

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(age, height, weight)? (<ipython-input-64-1ece668ff2de>, line 1)

In [65]:
print (age, height, weight)

21 5.5 130


In [66]:
profile()

(21, 5.5, 130)

In [67]:
print(profile())

(21, 5.5, 130)


In [68]:
store_list = ['Wendys', 'Chipotle', 'Starbucks', 'Dunkin', 'Taco Bell']

In [69]:
for position, name in enumerate(store_list):
    print position, name

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(position, name)? (<ipython-input-69-775ead449f37>, line 2)

In [70]:
for position, name in enumerate(store_list):
    print(position,name)


0 Wendys
1 Chipotle
2 Starbucks
3 Dunkin
4 Taco Bell


In [71]:
store_map = dict((name,position) for position, name in enumerate(store_list))

In [72]:
store_map

{'Wendys': 0, 'Chipotle': 1, 'Starbucks': 2, 'Dunkin': 3, 'Taco Bell': 4}

In [73]:
num_list = range(15)

In [74]:
num_list

range(0, 15)

In [76]:
list(num_list)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [77]:

reversed(list(num_list))

In [78]:
list(reversed(num_list))

[14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [109]:
subjects = ['math', 'stats', 'algebra']


In [110]:
subject_count = ['one', 'two', 'three']

In [111]:
total_subjects = zip(subjects, subject_count)
total_subjects

In [86]:
total_subjects

In [87]:
sub = ['math', 'algebra', 'stats']

In [88]:
sub_count = ['one', 'two', 'three']

In [89]:
total_sub = zip(sub, sub_count)

In [90]:
total_sub

In [101]:
a = (1, 2, 3)
b = ("Jenny", "Christy", "Monica")

In [102]:
c = zip(a,b)

In [106]:
c

In [94]:
zip( ['math', 'algebra', 'stats'], ['one', 'two', 'three'])

In [95]:
for i in zip([1,2,3],['a','b','c']):
    print(i)

(1, 'a')
(2, 'b')
(3, 'c')


In [96]:
p = zip([1,2,3],['a','b','c'])

In [108]:
p

In [114]:
z = zip([1,2,3],['a','b','c'])

In [115]:
z

In [116]:
print(z)

In [117]:
a = ['aliya', 'adnan', 'zoyu']

In [118]:
b = [1,2,3]

In [121]:
for i in zip(a,b):
    print(i)


('aliya', 1)
('adnan', 2)
('zoyu', 3)


In [122]:
type(i)

tuple

In [123]:
new = i

In [124]:
new

('zoyu', 3)

In [125]:
x = (1,2,3)
y = (4,5,6)


In [126]:
z=zip(x,y)

In [127]:
z

In [132]:
age = 16

In [133]:
if age<18:
    print ('minor')
else:
    print ('adult')

minor


In [3]:
word = "Encyclopedia"

In [10]:
't' in word

False

In [13]:
test_score1 = 23,25,54


In [18]:

test_score2 = 27, 65

In [19]:
test_score = test_score1 + test_score2

In [20]:
test_score

(23, 25, 54, 27, 65)

In [22]:
fname = 'George'

In [24]:
lname = 'Washington'

In [25]:
name = fname + lname 

In [26]:
name

'GeorgeWashington'

In [27]:
print(name)

GeorgeWashington


In [30]:
print(fname)

George


In [31]:
name = friend*3

NameError: name 'friend' is not defined

In [32]:
name = 'friend' * 3

In [33]:
name

'friendfriendfriend'

In [37]:
def my_first_function(name) : return(name)

In [39]:
print my_first_function('Jack')

SyntaxError: invalid syntax (<ipython-input-39-ad1bcb38437d>, line 1)

In [40]:
def add_two_numbers(num1, num2) : return num1 + num2

In [41]:
number1 = 23

In [42]:
number2 = 46

In [43]:
result = add_two_numbers(number1, number2)

In [44]:
result

69

In [45]:
print(result)

69


In [46]:
def profile():
    age = 21
    height = 5.6
    weight = 123
    return age, height, weight

In [47]:
profile()

(21, 5.6, 123)

In [50]:
print(age, height, weight)

21 5.6 123


In [49]:
age, height, weight = profile()

In [51]:
#enumerate takes care of the indices or positions
store_list = ['Dunkin', 'Taco Bell', 'Wendys', 'Chipotle', 'Dunkin']

In [52]:
store_list

['Dunkin', 'Taco Bell', 'Wendys', 'Chipotle', 'Dunkin']

In [53]:
enumerate(store_list)

In [55]:
for position, name in enumerate (store_list):
    print (position, name)

0 Dunkin
1 Taco Bell
2 Wendys
3 Chipotle
4 Dunkin


In [56]:
store_map = dict((name, position) for position, name in enumerate (store_list)):
    print(position, name)

SyntaxError: invalid syntax (<ipython-input-56-9d37a5dd7d47>, line 1)

In [58]:
store_map = dict((name, position) for position, name in enumerate (store_list))
print(position, name)

4 Dunkin


In [59]:
store_map

{'Dunkin': 4, 'Taco Bell': 1, 'Wendys': 2, 'Chipotle': 3}

In [60]:
sorted([24,65,2,4,69])

[2, 4, 24, 65, 69]

In [61]:
sorted("Data Science")

[' ', 'D', 'S', 'a', 'a', 'c', 'c', 'e', 'e', 'i', 'n', 't']

In [62]:
num_list = range(15)

In [63]:
num_list

range(0, 15)

In [64]:
list(reversed(num_list))

[14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [65]:
list(reversed(reversed(num_list)))

TypeError: 'range_iterator' object is not reversible

In [66]:
list1 = ['1','2','3']

In [67]:
list2 = ['4','5','6']

In [68]:
list = zip(list1, list2)

In [69]:
list

In [70]:
for a in list1 , list2 zip(list1, list2):
    print(list)

SyntaxError: invalid syntax (<ipython-input-70-c9f6a965a67b>, line 1)

In [71]:
marks = 81

In [72]:
if marks>90:
    print('Grade A')
elif 80<marks<90:
    print('Grade B')
elif 70<marks<80:
    print('Grade C')
else:
    print('Grade D')
    

Grade B


In [73]:
temperature = 100
while temperature > 95:
    print(temperature)
    temperature = temperature - 1

100
99
98
97
96


In [74]:
def test_float(number):
    return float(number)

In [75]:
test_float(3.2)

3.2

In [76]:
test_float('test_float')

ValueError: could not convert string to float: 'test_float'

In [77]:
import numpy as np

In [78]:
distance = [10,15,17,21]

In [79]:
time = [.30 , .47 , .54 , 1.23]

In [80]:
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time

In [81]:
speed

array([33.33333333, 31.91489362, 31.48148148, 17.07317073])

In [89]:
first_numpy_array = np.array([1,2,3,4,5,6])

In [90]:
first_numpy_array

array([1, 2, 3, 4, 5, 6])

In [91]:
print(first_numpy_array)

[1 2 3 4 5 6]


In [92]:
array_with_zeros = np.zeros((3,5))

In [87]:
array_with_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
array_with_empty = np.empty((5,3))

In [96]:
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
np.random

<module 'numpy.random' from 'C:\\Users\\aliya\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [99]:
np.random((2,3))

TypeError: 'module' object is not callable

In [100]:
np.random.seed(3)

In [103]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
np_arange=np.arange(12)

In [105]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [109]:
np_arange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [112]:
np_linspc = np.linspace(1,10,6)

In [113]:
np_linspc

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [114]:
np_ls = np.linspace(1,20,5)

In [115]:
np_ls

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [116]:
print(np_ls)

[ 1.    5.75 10.5  15.25 20.  ]


In [117]:
oneD_array = np.arange(15)

In [118]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [119]:
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [121]:
twoD_array = oneD_array.reshape(3,5)

In [122]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [123]:
threeD_array = np.arange(27).reshape(3,3,3)

In [124]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
oneD_array.ndims

AttributeError: 'numpy.ndarray' object has no attribute 'ndims'

In [126]:
oneD_array.ndim

1

In [127]:
twoD_array.ndim

2

In [128]:
oneD_array.shape

(15,)

In [129]:
twoD_array.shape

(3, 5)

In [130]:
threeD_array.shape

(3, 3, 3)

In [131]:
threeD_array.size

27

In [132]:
twoD_array.size

15

In [133]:
oneD_array.size

15

In [134]:
oneD_array.dtype

dtype('int32')

In [135]:
twoD_array.dtype

dtype('int32')

In [136]:
threeD_array.dtype

dtype('int32')

In [137]:
np.add(45,20)

65

In [139]:
np.subtract(3,5)

-2

In [143]:
np_daily_wage = np.array([7,19,56,46,31])*15

In [144]:
np_daily_wage

array([105, 285, 840, 690, 465])

In [145]:
print(np_daily_wage)

[105 285 840 690 465]


In [146]:
sum(np_daily_wage)

2385

In [150]:
np.logical_and(np_weekly_hours>20, np_weekly_hours<65)

array([ True,  True,  True, False,  True])

In [148]:
np_weekly_hours = np.array([23,45,50,20,55])